### ISSUE TITLE
Bluetooth issues with headsets

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#14]
This bug is so long already, that I doubt that it's fixable.

Streaming audio over bluetooth headsets doesn't work properly with most of the models. Various audio issues happen.

**Comment by MarcKe** [comment]
Did you ever have that issue?

**Comment by JustArchi** [comment]
I confirmed this issue, but I don't use BT myself.

**Comment by PhilTee** [comment]
Have just found that this bug only occurs when 3G data is enabled.
If the phone is forced down to 2G only, the distortion is gone.

**Comment by DimitriMayakovsky** [comment]
Maybe add this in Boardconfig

BOARD_USES_LEGACY_ALSA_AUDIO := true

**Comment by Damiano1997** [comment]
Hello,
I don't know if it's the same bug, but when I listen to music with BT,  the music stops for 0.5 second every 20-30 seconds.

**Comment by MarcKe** [comment]
Our device does not use alsa

**Comment by metalgear** [comment]
notice the Resurrection Remix builds based on slim/omni don't have the bluetooth music issues, so maybe the answer to the issue can be learned from their code bases?

**Comment by JustArchi** [comment]
No, they have the same issues we do.

**Comment by MarcKe** [comment]
This issues is totally random. I just got some new bluetooth headset and guess what, everything is fine.

**Comment by MarcKe** [comment]
And btw, resurrection remix is just a kang of CM, not more and not less.

**Comment by metalgear** [comment]
OK ,apologies. My tests showed that on other CM builds I would suffered audio loss within 15 minutes, but under RR over an hour passes no audio loss. It could just be random as you say then, which is just weird. I'll keep my eye on things and sadly have to stick to 4.4.2 ports for the meantime as it is my primary use for the device due to the nature of my job. Sorry to inconvenience!

**Comment by Gratje** [comment]
I started using cyanogenmod since 10.2 and sine then the bluetooth sound issue is there. I hope you guys can solve this problem.
Everytime i make a phone call connected to my bluetooth car stereo the sound is very distorted. Like @PhilTee mentioned the problems are gone when the preferred network is set to 2G. Sometimes when you have distorted sound on the car stereo and you switch to phone speaker the sound is also corrupted, so maybe the issue with distorted calling is related. I've installed weekly 5 and a stock kernel.

I generated logcat files when i made calls with 3G enabled and with 2G enabled. When I switched back from 2G to 3G and made a phone call, dialer crashed (new problem). Before calling I waited for the H+ sign but during calling it disappeared and the dialer crashed.

Logcat files:
https://www.dropbox.com/sh/8wv502wff2r4w6n/AAA-uUo9c4J8AVUWaox4NIYla?dl=0

Order:
Switched on bluetooth, enabled 3G, started logcat, made call (distorted), saved and cleared logcat, set preferred to 2G, made call (OK), saved and cleared logcat, switched back to 3G, made call (dialer crash), saved logcat

Same issue:
https://jira.cyanogenmod.org/browse/CYAN-2884

Thanks, good luck and keep up the good work!

**Comment by BikeAtor** [comment]
I had same Problem with CM11. I fixed most of the problems by using Boeffla-Kernel and changed Modem to murata.
See http://forum.xda-developers.com/galaxy-s3/help/cm10-solved-bluetooth-audio-streaming-t2038273/page4
Boeffla-Kernel is already available for CM12. I don't know if murata is available for CM12.

**Comment by JustArchi** [comment]
I was able to confirm this issue with my new samsung level box mini.

**Comment by JustArchi** [comment]
This is definitely device-based.

```
E/RILJ    ( 3405): Exception processing unsol response: 11017Exception:java.lang.RuntimeException: Unrecognized unsol response: 11017
E/RILJ    ( 3405): Exception processing unsol response: 11010Exception:java.lang.RuntimeException: Unrecognized unsol response: 11010
```

I bet it's because we don't handle these unsol responses. Maybe I could add a proper handler.

**Comment by mjm4456** [comment]
for me it worked after changing the modem firmware to "murata" even without need to change the kernel.
Because the "murata" firmware is already in the image this change could be done easy via adb:

$ adb shell
root@m0:/ $ su
root@m0:/ # cd /system/bin
root@m0:/system/bin # mount  -o remount,rw /system
root@m0:/system/bin # ls bcm*
bcm4334.hcd bcm4334_murata.hcd bcm4334_semco.hcd bcm4334_semcosh.hcd
root@m0:/system/bin # mv bcm4334.hcd bcm4334.hcd.ori
root@m0:/system/bin # cp bcm4334_murata.hcd bcm4334.hcd
root@m0:/system/bin # mount  -o remount,ro /system

That's it!  (no more distortion no more reboots ;-)

**Comment by JustArchi** [comment]
AD includes BCM profiling since long time already and it does not solve all issues.

**Comment by thopiekar** [comment]
It also happends for me, but only when Wifi is used at the same time. It also throttles the WiFi bandwidth.
In weekly 3 the UI crashed ( soft reboot ).

**Comment by snaif2** [comment]
Same for me. Soft reboot when i'm playing a song on every app i have. The only solution is to remian the display turned ON for me now. Battery consumption obviously increase (sry for bad english)

**Comment by JustArchi** [comment]
My latest reverse-engineering resulted in theory that various devices use totally different BT protocol when in use with Samsung devices. Faking our device to non-Samsung and forcing it to use standard protocol sounds like a workaround.

Low priority for now, as I don't even know where to start.

**Comment by Herby1209** [comment]
My S3 used to fast-restart when used with the JBL Charge 2 after 2 Minutes or less. Only way to keep using it was to keep the screen active.
Now i tried the performance Govenors and had no problems for 2 weeks.

Hope this might help you guys.

**Comment by leleobhz** [comment]
I suffer since cm11 with A2DP audio. I think its related to BT Coex and happens with any Archi/Arter/Nameless kernels.

If Wifi transfer data, A2DP stream got cracked and the error in logcat is 

W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 119 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 118 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 119 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 118 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 119 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 118 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 119 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 118 max_frames 124 nb_frame 7
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 115 max_frames 124 nb_frame 14
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 114 max_frames 124 nb_frame 14
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 113 max_frames 124 nb_frame 14
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 112 max_frames 124 nb_frame 14
W/bt-btif ( 8305): btif_media_aa_prep_2_send() - TX queue buffer count 111 max_frames 124 nb_frame 14

(A loooot).

Also, firmwares md5:

root@m0:/system/etc/wifi # md5sum /system/etc/wifi/bcmdhd_* /system/vendor/firmware/bluetooth/*                                                                          
c6a326e7d16c0626193d97db0d41a578  /system/etc/wifi/bcmdhd_apsta.bin_b2
03d32af6a22ac1593563c0bad00b4f80  /system/etc/wifi/bcmdhd_mfg.bin_b2
aa0e8c9deaafe84aa94dbf79127d0ecf  /system/etc/wifi/bcmdhd_p2p.bin_b2
bea486fe2e47f6793386e3f21361c927  /system/etc/wifi/bcmdhd_sta.bin_b2
3f8c4084ae4fd90b4e29c700c1247bd6  /system/vendor/firmware/bluetooth/bcm4334.hcd
3f8c4084ae4fd90b4e29c700c1247bd6  /system/vendor/firmware/bluetooth/bcm4334_murata.hcd
d542467d89ae53c7eb13a97f328d031c  /system/vendor/firmware/bluetooth/bcm4334_semcosh.hcd

Change murata <-> semcosh does not change notting. Dunno if the .txt does some difference.

Now using NamelessRom n-2.1 - but happens with Arter/Temasek and Archidroid versions.

**Comment by BLooDLorD** [comment]
On build 9, using any bluetooth device caused reboot in 30 seconds to 1 minute.

**Comment by thopiekar** [comment]
For me it looks like being related to a power saving feature. Would be
interesting what happens when changing several power saving settings and
find out which value changes this behavior.

**Comment by mjm4456** [comment]
The behavior is quite strange: sometimes (seldom) it works for hours but mostly it reboots after a 1-2 minutes. Neither reboot nor a powerdown (including battery remove) nor deactivating WiFi nor changing power settings etc. etc. helps in case of failure - but on another day it works again.
Keeping the display on (by charging battery and corresponding developer setting) helps a bit but not always...
Strange is that it did not happen on recent CM11 but on earlier CM as well.
May be some other App keeps the device awake somehow.
(BTW: since faking the device to non-Samsung the playback speed is correct - but still reboots...)

**Comment by djschny** [comment]
How is this labelled as won't fix?

**Comment by JustArchi** [comment]
It is labelled as such because nobody is going to look into that issue.

**Comment by djschny** [comment]
Then why leave it open? The inability to listen to music via Bluetooth is a pretty big deal. Considering people listen to music for hours each day with their phone. If no one wants to actually tackle this than that is one thing, but it shouldn't be labeled as won't fix.

**Comment by JustArchi** [comment]
Labels are for developers, and they describe precisely how we feel about certain issue. If I'm the only developer in charge of fixing bugs, and I know that I spent too much time on certain one and still didn't find any solution, I mark it as won't fix.

You don't need to agree with my label, you can fix issue yourself if you feel brave.

Also this issue is not connected with listening music over BT at all, but rather phone calls only.
